### ISSUE TITLE
Error : instance member 'cropImage can't be accessed using static access

### ISSUE THREAD

**Issue by Mike6x** [thealteria/flutter_getx_template#1]
![image](https://user-images.githubusercontent.com/25998007/156910455-a9520ef8-f19b-43c1-9508-111a06d4909b.png)

 croppedFile = await ImageCropper.**cropImage(**
        compressQuality: 50,
        sourcePath: image.path,
        aspectRatioPresets: [
          CropAspectRatioPreset.square,
          CropAspectRatioPreset.ratio3x2,
          CropAspectRatioPreset.original,
          CropAspectRatioPreset.ratio4x3,
          CropAspectRatioPreset.ratio16x9
        ],

**Comment by thealteria** [comment]
Fixed in the new commit
