### ISSUE TITLE
Field 'context' has not been initialized

### ISSUE THREAD

**Issue by dbd5** [thealteria/flutter_getx_template#2]
Hello, 
Can't seen to get this template to run, here's the error I'm getting;
Amy thoughts?

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2684): The following LateError was thrown building MyApp(dirty):
I/flutter ( 2684): LateInitializationError: Field 'context' has not been initialized.
I/flutter ( 2684): 
I/flutter ( 2684): The relevant error-causing widget was:
I/flutter ( 2684):   MyApp MyApp:file:///Users/petros/StudioProjects/template/lib/main.dart:11:18

**Comment by getch04** [comment]
add context:context property inside Screenutils inside main.dart

**Comment by thealteria** [comment]
Just upgrade all the dependencies, specially **flutter_screenutil**
